import{a as S,S as R,i as n}from"./assets/vendor-Czviwze2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const E="54663882-ec3b2d69ddbcbb3faf32c451a",q="https://pixabay.com/api/",P=15;async function p(s,e){const o={key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:P};return(await S.get(q,{params:o})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),$=new R(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const e=s.map(o=>`
        <li class="gallery-item">
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o.likes}</p>
            <p><b>Views:</b> ${o.views}</p>
            <p><b>Comments:</b> ${o.comments}</p>
            <p><b>Downloads:</b> ${o.downloads}</p>
          </div>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",e),$.refresh()}function B(){m.innerHTML=""}function b(){h.classList.add("visible")}function L(){h.classList.remove("visible")}function v(){g.classList.add("visible")}function a(){g.classList.remove("visible")}const f=document.querySelector(".form"),M=document.querySelector(".load-more");let c="",i=1,u=0;const w=15;f.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.target.elements.search.value.trim(),!!c){i=1,B(),a(),b();try{const e=await p(c,i);if(u=e.totalHits,e.hits.length===0){n.error({message:"Sorry, no images found.",position:"topRight"}),a();return}y(e.hits),i*w>=u?(a(),n.info({message:"You've reached the end of search results.",position:"topRight"})):v(),f.reset()}catch{n.error({message:"Something went wrong",position:"topRight"})}finally{L()}}});M.addEventListener("click",async()=>{i+=1,b(),a();try{const s=await p(c,i);y(s.hits),i*w>=u?(a(),n.info({message:"You've reached the end of search results.",position:"topRight"})):v();const e=document.querySelector(".gallery-item");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{n.error({message:"Error loading images",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
