import{a as w,S,i as n}from"./assets/vendor-Czviwze2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const E="54663882-ec3b2d69ddbcbb3faf32c451a",R="https://pixabay.com/api/",q=15;async function f(r,e){const s={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q};return(await w.get(R,{params:s})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more"),P=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const e=r.map(s=>`
        <li class="gallery-item">
          <a href="${s.largeImageURL}">
            <img
              src="${s.webformatURL}"
              alt="${s.tags}"
            />
          </a>
        </li>
      `).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function B(){m.innerHTML=""}function y(){g.classList.add("visible")}function L(){g.classList.remove("visible")}function M(){p.classList.add("visible")}function b(){p.classList.remove("visible")}const u=document.querySelector(".search-form"),A=document.querySelector(".load-more");let a="",i=1,d=0;const v=15;u.addEventListener("submit",async r=>{if(r.preventDefault(),a=r.target.elements.search.value.trim(),!!a){i=1,B(),b(),y();try{const e=await f(a,i);if(d=e.totalHits,e.hits.length===0){n.error({message:"Sorry, no images found.",position:"topRight"});return}h(e.hits),i*v<d&&M(),u.reset()}catch{n.error({message:"Something went wrong",position:"topRight"})}finally{L()}}});A.addEventListener("click",async()=>{i+=1,y();try{const r=await f(a,i);h(r.hits),i*v>=d&&(b(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const e=document.querySelector(".gallery-item");if(e){const s=e.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}}catch{n.error({message:"Error loading images",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
